ALTER TABLE EMPLOYEE DROP FOREIGN KEY FK_EMPLOYEE_BRANCH_ID
ALTER TABLE SUPPLIES DROP FOREIGN KEY FK_SUPPLIES_DRUG_ID
ALTER TABLE SUPPLIES DROP FOREIGN KEY FK_SUPPLIES_SUPPLIER_ID
DROP TABLE CUSTOMER
DROP TABLE DRUG
DROP TABLE EMPLOYEE
DROP TABLE INSURANCE
DROP TABLE RECIPE
DROP TABLE SUPPLIER
DROP TABLE SUPPLIES
DROP TABLE WAREHOUSE
DROP TABLE WORKPLACE
